services:
  glpi:
    image: elestio/glpi:11.0.7
    container_name: app_glpi
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      GLPI_LANG: "es_ES"
      GLPI_DB_SERVER: "${DB_HOST}"
      GLPI_DB_PORT: "${DB_PORT}"
      GLPI_DB_DATABASE: "${DB_NAME}"
      GLPI_DB_USER: "${DB_USER}"
      GLPI_DB_PASSWORD: "${DB_PASSWORD}"
      GLPI_SKIP_AUTOINSTALL: "true"
      GLPI_SKIP_AUTOUPDATE: "true"
    volumes:
      - /opt/servicios/nodo-app-glpi/glpi_data:/var/www/html
